export const SET_ALERT = "SET_ALERT";
export const FETCH_USER = "FETCH_USER"
export const SHOW_FORUM_POST = "SHOW_FORUM_POST"
export const SHOW_MY_FORUM_POST = "SHOW_MY_FORUM_POST"
export const SHOW_TOPIC_WISE_FORUM_POST = "SHOW_TOPIC_WISE_FORUM_POST"
export const LOGOUT = "LOGOUT"

